name: Bump Tags on Master

on:
  workflow_dispatch:

jobs:
  bump-tags:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: master

      - name: Update all version tags
        run: |
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com
          
          # Update all version tags
          git tag -fa v4 -m "Update v4 tag to latest commit on master"
          git tag -fa v5 -m "Update v5 tag to latest commit on master"
          git tag -fa v5.1.0 -m "Update v5.1.0 tag to latest commit on master"
          git tag -fa v6 -m "Update v6 tag to latest commit on master"
          git tag -fa v6.0.1 -m "Update v6.0.1 tag to latest commit on master"
          git tag -fa v6.1.0 -m "Update v6.1.0 tag to latest commit on master"
          
          # Push all tags at once
          git push origin v4 v5 v5.1.0 v6 v6.0.1 v6.1.0 --force

      - name: Send Slack notification on success
        uses: slackapi/slack-github-action@v1
        with:
          payload: |
            {
              "text": "Updated all version tags (v4, v5, v5.1.0, v6, v6.0.1, v6.1.0) to the latest commit on master"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.CACHE_SLACK_WEBHOOK_URL }}
